<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<div style="margin:200px 0 0 600px;">
<form action="/default/auth/login" method="post">
<table>
<tr><td>用户名:</td><td><input type="text" name="username" /></td></tr>
<tr><td>密码:</td><td><input type="password" name="password" /></td></tr>
<tr><td colspan="2" align="center"><input type="submit" name="submit" value="登 录" />  <a href="/default/signup">注册</a> </td></tr>
</table>
</form>
</div>
</body>
</html>