<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/res/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="/res/css/layout.css"/>
</head>
<body class="auth-body">
<div class="auth-form" >
	<form action="/default/auth/login" method="post">
		<table>
			<tr><td>用户名:</td><td><input type="text" name="username" /></td></tr>
			<tr><td>密码:</td><td><input type="password" name="password" /></td></tr>
			<tr><td colspan="2" align="right"><input type="submit" name="submit" value="登 录" />  <a href="/default/signup">注册</a> </td></tr>
		</table>
	</form>
</div>
</body>
</html>