<div class="top-links">
    <span class="login-info">您好，<a href="javascript:void(0);" class="user-nick"><?php echo $this->userName;?></a></span>
      <span class="pipe">|</span>
                     
<!--           <select name="showMode" id="showMode">
              <option value="me"'+selectMe+'>我的任务</option>
              <option value="us"'+selectUs+'>大家的任务</option>
          </select> 
                     
          <span class="pipe">|</span>-->
          <a href="#" class="message">消息<span id="message-counter"><?php echo $this->messages;?></span></a>
          <span class="pipe">|</span>
                     
          <a href="#" class="signout">退出</a>
</div>