<div class="list-block scheduled-list">
	<?php foreach($this->lists as $key=>$list):?>
		<div>
			<div class="group-title"><?php echo substr($key,0,10);?></div>
			<ul class="task-list inactive-list">
				<?php echo $this->partial('me/tasklist.phtml','default',array('focusField'=>$this->focusField,'list'=>$list))?>
			</ul>
		</div>
	<?php endforeach;?>
</div>
<?php if(!empty($this->templates)):?>
<div class="list-block template-list">
	<div class="group-title">每周任务</div>
		<ul class="task-list inactive-list">
			<?php echo $this->partial('me/tasklist.phtml','default',array('focusField'=>$this->focusField,'list'=>$this->templates))?>
		</ul>
</div>
<?php endif;?>