<script type="text/javascript" src="/res/js/jquery.history.js"></script>
<script type="text/javascript"><!--

Date.prototype.setISO8601 = function(dString){
    var regexp = /(\d\d\d\d)(-)?(\d\d)(-)?(\d\d)(T)?(\d\d)(:)?(\d\d)(:)?(\d\d)(\.\d+)?(Z|([+-])(\d\d)(:)?(\d\d))/;
    if (dString.toString().match(new RegExp(regexp))) {
    var d = dString.match(new RegExp(regexp));
    var offset = 0;
    this.setUTCDate(1);
    this.setUTCFullYear(parseInt(d[1],10));
    this.setUTCMonth(parseInt(d[3],10) - 1);
    this.setUTCDate(parseInt(d[5],10));
    this.setUTCHours(parseInt(d[7],10));
    this.setUTCMinutes(parseInt(d[9],10));
    this.setUTCSeconds(parseInt(d[11],10));
    if (d[12])
    this.setUTCMilliseconds(parseFloat(d[12]) * 1000);
    else
    this.setUTCMilliseconds(0);
    if (d[13] != 'Z') {
    offset = (d[15] * 60) + parseInt(d[17],10);
    offset *= ((d[14] == '-') ? -1 : 1);
    this.setTime(this.getTime() - offset * 60 * 1000);
    }
    }
    else {
    this.setTime(Date.parse(dString));
    }
    return this;
};




	function list(done,userId,page){
		url = 'done='+done+'&userId='+userId+'&page='+page+'&app=list';
		$.getJSON('/api/tasks/search',{done:done,userId:userId,page:page,perPage:10},function(data){

			var tasks = {};
			tasks["noExeDate"] = [];
			
			$.each(data.data, function(index, item){
				if(item.exeDate==''){
					tasks["noExeDate"].push(item);
				}
				
				if ($.isEmptyObject(tasks[item.exeDate])) {
					tasks[item.exeDate] = [];
					tasks[item.exeDate].push(item);
				} else {
					tasks[item.exeDate].push(item);
				}
				
			});
			
			var content = '';

			$.each(tasks,function(index, item){
				if(!$.isEmptyObject(item)){
					if(index==0){
						content += '<div class="listing"><a href="#" class="listing_title"><b>尚未安排的任务</b></a><ul class="listing_box">';
						$.each(item,function(key,value){
							var commentsNum = value.comments>0?('<em>评论数:'+value.comments+'</em>'):'';
							content += '<li class="tasklist"><a href="#done='+done+'&userId='+userId+'&page='+page+'&taskId='+value._id+'" class="row" id="'+value._id+'"><span class="area"><strong class="mark">'+value.username+'</strong></span><b>'+value.title+'</b>'+commentsNum+'</a></li>';
						});
						content += '</ul></div>';
					}else{
						content += '<div class="listing"><a href="#" class="listing_title"><b>'+item[0].exeMonth+'月'+item[0].exeDay+'日</b></a><ul class="listing_box">';
						$.each(item,function(key,value){
							var commentsNum = value.comments>0?('<em>评论数:'+value.comments+'</em>'):'';
							content += '<li class="tasklist"><a href="#done='+done+'&userId='+userId+'&page='+page+'&taskId='+value._id+'" class="row" id="'+value._id+'"><span class="area"><strong class="mark">'+value.username+'</strong></span><b>'+value.title+'</b>'+commentsNum+'</a></li>';
						});
						content += '</ul></div>';
					}

				}
			});
			var nextPage = (data.currentPage+1)>data.totalPage?data.totalPage:(data.currentPage+1);
			content += '<span class="tool">'+data.currentPage+'/'+data.totalPage+' 页 <a href="javascript:void(0);" onclick="list('+done+','+userId+',1);">首页</a> <a href="javascript:void(0);" onclick="list('+done+','+userId+','+(data.currentPage-1)+');">上一页</a> <a href="javascript:void(0);" onclick="list('+done+','+userId+','+nextPage+');">下一页</a> <a href="javascript:void(0);" onclick="list('+done+','+userId+','+data.totalPage+');">末页</a></span><div class="blank"></div>';
			$('.box_right').html(content);

			var unfinishedClass = (done==true || done=='true')?'done':'done selected';
			var finishedClass = (done==true || done=='true')?'done selected':'done';
			var topMenu = '<a href="javascript:void(0)" class="'+finishedClass+'" id="finished">已完成</a><a href="javascript:void(0)" class="'+unfinishedClass+'" id="unfinished">未完成</a><span id="topPaginator"><a href="javascript:void(0);" onclick="list('+done+','+userId+','+nextPage+');" class="prev">下一页</a><a href="javascript:void(0);" onclick="list('+done+','+userId+','+(data.currentPage-1)+');" class="next">上一页</a></span>';
			$('.process').html(topMenu);
			//console.log(content);
		});
	}
	
	$(function(){

		$.history.init(function(url) {
            if(!url){
            	list(true,0,1);
            }else{
				if(url.split('&').length>3){
					if(url.split('&')[3].split('=')[0]=='app'){
						list(url.split('&')[0].split('=')[1],url.split('&')[1].split('=')[1],url.split('&')[2].split('=')[1]);
					}
				}
            }
        });
		
		$('.userlist').live('click',function(){
			$('.userlist').each(function(){
				$(this).removeClass('selected');
			});
			var userId = $(this).attr('id');
			$(this).addClass('selected');
			list(true,userId,1);
		});

		$('.all').click(function(){
			$('.userlist').each(function(){
				$(this).removeClass('selected');
			});
			list(true,0,1);
		});

		$('#finished').live('click',function(){
			var userId = $('.navi>.selected').attr('id');
			list(true,userId,1);		
		});

		$('#unfinished').live('click',function(){
			var userId = $('.navi>.selected').attr('id');
			list(false,userId,1);		
		});

		$('.tasklist>.row').live('click',function(){
			var taskId = $(this).attr('id');
			$.get('/api/tasks/show',{id:taskId},function(data){
				var objDate = new Date();
				objDate.setISO8601(data.doneTime);
				var content = '<div class="listing">';
				content += '<a href="javascript:void(0)" class="listing_title"><b>'+data.title+'</b></a>';
				content += '<ul class="listing_box">';
				content += '<li><a href="javascript:void(0)" class="row"><span class="title">备注：</span><b>'+data['note']+'</b></a></li>';
				content += '<li><a href="javascript:void(0)" class="row"><span class="title">开始时间：</span><b>'+(data['exeDate']==0?'---':data['exeDate'])+'</b></a></li>';
				content += '<li><a href="javascript:void(0)" class="row"><span class="title">完成时间：</span><b>'+(data.doneTime==0?'---':objDate.getFullYear()+'-'+(objDate.getUTCMonth()+1)+'-'+objDate.getUTCDate()+'  '+objDate.getHours()+':'+objDate.getMinutes())+'</b></a></li>';
				content += '</ul>';
				content += '</div>';
				content += '<div class="listing"><a href="javascript:void(0)" class="listing_title"><b>已有评论</b></a><ul class="listing_box" id="commentsList">';
				content += '</ul></div>';

				content += '<div class="listing"><a href="javascript:void(0)" class="listing_title"><b>添加评论</b></a><ul class="listing_box">';
				content += '<li><textarea name="" class="add_comment" cols="" id="commentContent" rows=""></textarea><input type="hidden" name="taskId" id="currentTaskId" value="'+taskId+'" /><input name="" id="add_btn" class="add_btn" type="button" value="添&nbsp;加" /></li>';
				content += '</ul></div>';
				content += '<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>';
				$('.box_right').html(content);
				$('.process').html('<a href="javascript:void(0)" class="done" id="goback">返&nbsp;&nbsp;回</a><span id="topPaginator"></span>');
				$.getJSON('/api/comments/search',{id:taskId},function(data){
					var content = '';
					for(var i in data){
						var objDate = new Date();
						objDate.setISO8601(data[i].createdTime);
						content += '<li><b class="comment_title">'+data[i]['username']+'   发表于'+objDate.getFullYear()+'年'+(objDate.getUTCMonth()+1)+'月'+objDate.getUTCDate()+'日  '+objDate.getHours()+':'+objDate.getMinutes()+'</b><strong class="comment_box">'+data[i]['content']+'</strong></li>';
					}
					$('#commentsList').append(content);
				});
			},'json');
		});

		$('#goback').live('click',function(){
            $.history.load(url);
            return false;
		});

		$('#add_btn').live('click',function(){
			var content = $('#commentContent').val();
			if(content==''){
				alert('评论内容不能为空!');
				return false;
			}
			var taskId = $('#currentTaskId').val();
			var content = $('#commentContent').val();
			$.post('/api/comments/create',{taskId:taskId,comment:content},function(data){
				if(data='true'){
					$('#commentContent').val('');
					$.getJSON('/api/comments/search',{id:taskId},function(data){
						var content = '';
						for(var i in data){
							var objDate = new Date();
							objDate.setISO8601(data[i].createdTime);
							content += '<li><b class="comment_title">'+data[i]['username']+'   发表于'+objDate.getFullYear()+'年'+(objDate.getUTCMonth()+1)+'月'+objDate.getUTCDate()+'日  '+objDate.getHours()+':'+objDate.getMinutes()+'</b><strong class="comment_box">'+data[i]['content']+'</strong></li>';
						}
						$('#commentsList').html(content);
					});
				}
			},'json');
		});
		
	});
</script>