
<div class="listing">
<a href="#" class="listing_title"><b>编辑任务</b></a>
<form>
<div class="listing_box">
<u><b>标题：</b><input name="title"id="title" class="add_title" type="text" /></u>
<u id="belongto"><b>所属：</b>
	<select name="box"id="box" >
	<option value="inbox">收集箱</option>
	<option value="today">今日待办</option>
	<option value="schedule">日程</option>
	<option value="someday">择日待办</option>
</select> 
<input name="exeDate" id="exeDate" class="add_time" type="text"readonly="readonly">
</u> 
<u><b>备注：</b><textarea name="note"id="note" class="add_box" cols="" rows=""></textarea></u>
<div><a href="#"id="repeat">重复</a><span id="repeat_info"></span></div>
<input id="submit"name="" class="add_btn" type="button" value="提交" />
</div>
</form>
<div id="dialogRepeat" title="repeat">
<div id="repeat_form">
<u><b>重复方式:</b></u>
<select name="repeatType" id="repeatType">
	<option value="daily" >按日</option>
	<option value="weekly" >按周</option>
	<option value="monthly" >按月</option>
	<option value="yearly" >按年</option>
</select>
<div id="repeatDetail"></div>
</div>
</div>

</div>
<script type="text/javascript">
$(document).ready(function(){	 
	var box= "<?php echo $this->box;?>";
	var taskId= "<?php echo $this->taskId;?>";
	var weekdays='';
	var editRepeat='false';
	var repeatId;
	var templateId;
	var today=new Date();
	
	var repeatType='';
    var frequency=0;
    var days='';
    $("#box").val(box);
    if(box!="schedule"){
		 $("#exeDate").hide();
	}
$.getJSON("/api/tasks/edit",{taskId:taskId},function(data){
  $("#title").val(data.task.title);
  $("#note").val(data.task.note);
  $("#exeDate").val(data.task.exeDate);
  if(data.repeat){
	  var x;
	  $("#repeatType").val(data.repeat.type);
	  $("#frequency").val(data.repeat.frequency);
	  repeatTypeChange();
	  weekdays=','+data.repeat.days;
	  days=data.repeat.days.split(',');	
	  $("#repeat_info").append(' '+'<span>每'+data.repeat.frequency+'周</span>'+':');  
	  for(x in days){    
	      $("#weekday_"+days[x]).attr("checked",true); 		
          $("#repeat_info").append('星期'+days[x]+' ');
	  } 
  }
  templateId=data.task.template;
  repeatId=data.task.repeatId;
  if(repeatId>0||box=='done'||box=='deleted'){
     $("#belongto").hide(); 
  }
});
$("#box").change(function(){
     boxChange();
});
	
$( "#exeDate" ).datepicker({
		//showButtonPanel: true ,
		dateFormat: 'yy-mm-dd',
		monthNames: ['一月','二月','三月','四月','五月','六月',
			 			'七月','八月','九月','十月','十一月','十二月'], // Names of months for drop-down and formatting			 		
        dayNamesMin: ['日','一','二','三','四','五','六'],
		minDate: 1
		
});	
	
    $("#submit").click(function(){
        var exeDate=$("#exeDate").val();
        var title=$("#title").val();
        var note=$("#note").val();
       
        $.post("/api/tasks/edit",{editRepeat:editRepeat,taskId:taskId,repeatId:repeatId,templateId:templateId,exeDate:exeDate,title:title,note:note,box:$("#box").val(),repeatType:repeatType,frequency:frequency,days:days},function(){
        	window.location.href="/task/index/box/"+box;
            });
 });

	$("#dialogRepeat").dialog({
        autoOpen: false,
        width: 500,
        buttons:{
       "确定":function(){
		 if($("#frequency").val()>=1&&weekdays!=''){ 		 	 			  			
	  			repeatType=$("#repeatType").val();
	 		    frequency=$("#frequency").val();		
	  	        editRepeat='true';
	  	        
		  	    days=weekdays.substr(1);
	    	    var repeat_info_days=days.split(',');
	            repeat_info_days=repeat_info_days.sort();
	            $("#repeat_info").html(' '+'<span>每'+frequency+'周</span>'+':');
	            for(var x in repeat_info_days){
	            $("#repeat_info").append('星期'+repeat_info_days[x]+' ');}
	  	       }else{
	  	    	   editRepeat='false';
	  		       }
	        $(this).dialog("close");
	       },
       "取消":function(){
	        editRepeat='false';
        $(this).dialog("close");
           }
        }
		});
	$("#repeat").click(function(){
        $("#dialogRepeat").dialog("open");
		});
	$("#repeatType").change(function(){
		repeatTypeChange();
		});

	$(":checkbox").live('click',function(){
		if($(this).attr("checked")==true){weekdays=weekdays+','+$(this).attr("value");}
		else{
			var str;
			str=','+$(this).val();
			weekdays=weekdays.replace(new RegExp(str,"g"),"");
			}
		});
	function boxChange(){
	   	 if($("#box").val()=="schedule"){
				 $("#exeDate").show();
				if($("#exeDate").val()==0){				
					 $( "#exeDate" ).val(today.getFullYear()+"-"+addZero((today.getMonth()+1))+"-"+addZero((today.getDate()+1)));
				}
		}else{
			$("#exeDate").hide();
			}
	}
	function repeatTypeChange(){
		var content;
		if($("#repeatType").val()=='weekly'){
         content='<p>重复频率：每<input id="frequency" name="frequency" type="text" size="3" value="1"></input>周</p>'
        + '<p>重复日：<input type="checkbox" id="weekday_1"value="1">周一</input>&nbsp;<input type="checkbox" id="weekday_2"value="2">周二</input>&nbsp;<input type="checkbox" id="weekday_3"value="3">周三</input>&nbsp;<input type="checkbox" id="weekday_4"value="4">周四</input>&nbsp;<input type="checkbox"id="weekday_5" value="5">周五</input>&nbsp;<input type="checkbox" id="weekday_6"value="6">周六</input>&nbsp;<input type="checkbox" id="weekday_7"value="7">周日</input>&nbsp;</p>';
          }
      else{
          content='暂不支持';
          }
      $("#repeatDetail").html(content);
      $("#frequency").change(function(){
          $("#frequency").val(parseInt($("#frequency").val()));
      });
     }
   function addZero(s){
      return ("00"+s).substr((s+"").length);
	   }
});
</script>