<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Layout</title>
<link rel="stylesheet" type="text/css" href="/res/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="/res/css/layout.css"/>
<link rel="stylesheet" type="text/css" href="/res/css/theme-default.css"/>
<link rel="stylesheet" type="text/css" href="/res/css/ui/cupertino/jquery-ui-1.8.5.custom.css"/>

<script src="/res/js/jquery-1.4.2.min.js" type="text/javascript"></script>
<script src="/res/js/jquery-ui-1.8.5.custom.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/res/js/jquery.history.js"></script>
<script src="/res/js/tt.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/toppanel.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/sidebar.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/toolbar.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/mainpanel.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/dialogs.js?v=1.js" type="text/javascript"></script>

</head>
<body>

<script>

</script>

<div id="container">
  <div id="header">
    <h1><a href="#"><span>ThingsLife</span></a></h1>
  </div>
  <div id="main">
    <div id="sidebar"></div>
    <div id="content-wrap">
      <div id="content">
      <div id="content-list"></div>
      <div id="content-detail"></div>
      </div>
      <div id="toolbar"></div>
    </div>
  </div>
</div>

<div id="date-dialog" title="日期" class="dialog hidden"></div>
<div id="new-edit-dialog" class="dialog hidden task-form" title=""></div>
<div id="repeat-dialog" class="dialog hidden"></div>
<div id="dueDate-dialog" class="dialog hidden"></div>
<div id="text-dialog" class="dialog hidden" title="评论"></div>
</body>
</html>