<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>ThingsLife</title>
<link rel="stylesheet" type="text/css" href="/res/css/reset.css" />
<link rel="stylesheet" type="text/css" href="/res/css/layout.css" />
<link rel="stylesheet" type="text/css" href="/res/css/theme.css" />
<link rel="stylesheet" type="text/css" href="/res/css/ui/cupertino/jquery-ui-1.8.5.custom.css"/>

<script src="/res/js/libs/jquery-1.4.4.min.js" type="text/javascript"></script>
<script src="/res/js/libs/jquery-ui-1.8.8.min.js" type="text/javascript"></script>
<script src="/res/js/libs/jquery.autogrow.js" type="text/javascript"></script>


<script src="/res/js/tt.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/toppanel.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/sidebar.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/toolbar.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/taskContent.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/mainpanel.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/dialogs.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/task.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/taskList.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/swfobject.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/libs/ajaxfileupload.js?v=1.js" type="text/javascript"></script>
<script type="text/javascript">
/*$(function() {
	SidebarPanel.bootstrap({
		type : "focus"
	});

	$(window).resize();
	
	var task = new Task({id: 1, name: "task_1"});
	
	
});?*/
</script>
</head>
<body>

<div id="container">
  <div id="header">
    <h1>ThingsLife</h1>
    
  </div>
  <div id="focus-panel">
  </div>
  <div id="content">

  
  
    <p>END content</p>
  </div>
  
  <div id="toolbar">
   toolbar
  </div>
  
</div>
<div id="date-dialog" title="日期" class="dialog hidden" style="display:none"></div>
<div id="new-edit-dialog" class="dialog hidden task-form" title="" style="display:none"></div>
<div id="repeat-dialog" class="dialog hidden" style="display:none"></div>
<div id="text-dialog" class="dialog hidden" title="消息" style="display:none"></div>
<div id="canvas-dialog" class="dialog hidden" title="画布" style="display:none " ></div>
<div id="Record-dialog" class="dialog hidden" title="录音" style="display:none " ></div>
</body>
</html>