<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>ThingsLife</title>
<link rel="stylesheet" type="text/css" href="/res/css/reset.css" />
<link rel="stylesheet" type="text/css" href="/res/css/layout.css" />
<link rel="stylesheet" type="text/css" href="/res/css/theme.css" />
<link rel="stylesheet" type="text/css" href="/res/css/ui/cupertino/jquery-ui-1.8.5.custom.css"/>


<script type="text/javascript">
config=[];
</script>
</head>
<body>

<div id="container">
  <div id="header">
    <h1>ThingsLife</h1>
    <?php echo $this->action('head', 'me')?>
  </div>
  <div id="focus-panel">
  	<?php echo $this->action('sidebar','me')?>
  </div>
  <div id="content">
  
    <p>END content</p>
  </div>
  
  <div id="toolbar">
  </div>
  
</div>
</div>
<div id="text-dialog" class="dialog hidden" title="消息" style="display:none"></div>
<div id="Record-dialog" class="dialog hidden" title="录音" style="display:none " ></div>


</body>
<script src="/res/js/libs/jquery-1.7.min.js" type="text/javascript"></script>
<script src="/res/js/libs/jquery-ui-1.8.8.min.js" type="text/javascript"></script>
<script src="/res/js/libs/jquery.autogrow.js" type="text/javascript"></script>

<script src="/res/js/tt.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/task.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/repeat.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/tag.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/template.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/dateDialog.js?v=1.js" type="text/javascript"></script>

<script src="/res/js/toppanel.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/sidebar.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/toolbar.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/mainpanel.js?v=1.js" type="text/javascript"></script>

<script src="/res/js/editDialog.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/newDialog.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/repeatDialog.js?v=1.js" type="text/javascript"></script>
<script src="/res/js/canvasDialog.js?v=1.js" type="text/javascript"></script>

<script src="/res/js/taskList.js?v=1.js" type="text/javascript"></script>
</html>